export const userInputs = [
  {
    id: 1,
    label: "First Name",
    type: "text",
    placeholder: "Enter First Name",
    variant: "filled",
    name: "firstname",
    xs: 4,
  },
  {
    id: 2,
    label: "Last Name",
    type: "text",
    placeholder: "Enter Last Name",
    variant: "filled",
    name: "lastname",
    xs: 4,
  },
  {
    id: 3,
    label: "MiddleName",
    type: "text",
    placeholder: "Enter Middle Name",
    variant: "filled",
    name: "middlename",
    xs: 4,
  },
  {
    id: 4,
    label: "Email",
    type: "text",
    placeholder: "Enter Email",
    variant: "filled",
    name: "email",
    xs: 4,
  },
  {
    id: 5,
    label: "Phone",
    type: "text",
    placeholder: "Enter Phone",
    variant: "filled",
    name: "phone",
    xs: 4,
  },
  {
    id: 6,
    label: "National ID",
    type: "text",
    placeholder: "Enter National ID",
    variant: "filled",
    name: "nid",
    xs: 4,
  },
  {
    id: 7,
    label: "Present Address",
    type: "text",
    placeholder: "Enter Present Address",
    variant: "filled",
    name: "present_address",
    xs: 6,
  },
  {
    id: 8,
    label: "Permanent Address",
    type: "text",
    placeholder: "Enter Permanent Address",
    variant: "filled",
    name: "permanent_address",
    xs: 6,
  },
];
